In [90]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [91]:
print("Classification Report:")
print(classification_report(Y_test, X_test_prediction))

print("Confusion Matrix:")
print(confusion_matrix(Y_test, X_test_prediction))

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      4696
           1       0.98      0.99      0.99      4284

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980

Confusion Matrix:
[[4631   65]
 [  60 4224]]

In [92]:
!wget -O fake-news.zip https://www.kaggle.com/api/v1/datasets/download/clmentbisaillon/fake-and-real-news-dataset
!unzip -o fake-news.zip

--2026-10-07 15:39:18--  https://www.kaggle.com/api/v1/datasets/download/clmentbisaillon/fake-and-real-news-dataset
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com:443/kaggle-data-sets/4831777/8165591/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20261007%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20261007T152611Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=330dc67791a92f1c7c513ac6240766e196b9305249e5d4d3c89066ba9eec695e3944b2a262a160e28180cbf115b441e27aa584e6be477c4db8542413226ca27d37c4931f0d6acd3607dfdd5b766e5db229e94b9c51795755f1c109d6974e71fc1b4d01d354146a1860444da085911b18abe2581ce932e6f59d83406397d952b41e91008fe30d14ecaa1187b4ad42c5caad78d377379a04f8e2e4fdb6a0979cafa51f04238bee5aa8599b7daef55f84cc172e447b758f32756ea04ee87c4ab3da23c7d6c71116e9d6f9a33b03120b20ecf26f515ec1ffaec7dac2ec1e42aed62144da0bff72b5f968350b495476be7f46adc88ded902be3275405922e959f26bb [following]
--2026-10-07 15:39:19--  https://storage.googleapis.com/kaggle-data-sets/4831777/8165591/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20261007%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20261007T152611Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=330dc67791a92f1c7c513ac6240766e196b9305249e5d4d3c89066ba9eec695e3944b2a262a160e28180cbf115b441e27aa584e6be477c4db8542413226ca27d37c4931f0d6acd3607dfdd5b766e5db229e94b9c51795755f1c109d6974e71fc1b4d01d354146a1860444da085911b18abe2581ce932e6f59d83406397d952b41e91008fe30d14ecaa1187b4ad42c5caad78d377379a04f8e2e4fdb6a0979cafa51f04238bee5aa8599b7daef55f84cc172e447b758f32756ea04ee87c4ab3da23c7d6c71116e9d6f9a33b03120b20ecf26f515ec1ffaec7dac2ec1e42aed62144da0bff72b5f968350b495476be7f46adc88ded902be3275405922e959f26bb
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.16.207, 142.251.179.207, 64.233.180.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.16.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42975911 (41M) [application/zip]
Saving to: ‘fake-news.zip’

fake-news.zip       100%[===================>]  40.98M   146MB/s    in 0.3s

2026-10-07 15:39:19 (146 MB/s) - ‘fake-news.zip’ saved [42975911/42975911]

Archive:  fake-news.zip
  inflating: Fake.csv
  inflating: True.csv

In [93]:
!unzip -o fake-news.zip

Archive:  fake-news.zip
  inflating: Fake.csv
  inflating: True.csv

In [94]:
fake_news = pd.read_csv("/content/Fake.csv")
true_news = pd.read_csv("/content/True.csv")

print("Fake news shape:", fake_news.shape)
print("True news shape:", true_news.shape)

Fake news shape: (23481, 4)
True news shape: (21417, 4)

In [95]:
print("Fake News Dataset:")
print(fake_news.head())

print("\nTrue News Dataset:")
print(true_news.head())

Fake News Dataset:
                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date
0  December 31, 2017
1  December 31, 2017
2  December 30, 2017
3  December 29, 2017
4  December 25, 2017

True News Dataset:
                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date
0  December 31, 2017
1  December 29, 2017
2  December 31, 2017
3  December 30, 2017
4  December 29, 2017

In [96]:
fake_news["label"] = 0
true_news["label"] = 1
print(fake_news.head())
print(true_news.head())

                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...
1   Drunk Bragging Trump Staffer Started Russian ...
2   Sheriff David Clarke Becomes An Internet Joke...
3   Trump Is So Obsessed He Even Has Obama’s Name...
4   Pope Francis Just Called Out Donald Trump Dur...

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News
1  House Intelligence Committee Chairman Devin Nu...    News
2  On Friday, it was revealed that former Milwauk...    News
3  On Christmas day, Donald Trump announced that ...    News
4  Pope Francis used his annual Christmas Day mes...    News

                date  label
0  December 31, 2017      0
1  December 31, 2017      0
2  December 30, 2017      0
3  December 29, 2017      0
4  December 25, 2017      0
                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date  label
0  December 31, 2017       1
1  December 29, 2017       1
2  December 31, 2017       1
3  December 30, 2017       1
4  December 29, 2017       1

In [97]:
news_dataset = news_dataset.sample(
    frac=1,
    random_state=2
).reset_index(drop=True)
print(news_dataset.shape)
news_dataset.head()

(44898, 3)

,title,text,label
0,"Trump, Clinton court Ohio as White House race ...","CANFIELD, Ohio/CLEVELAND (Reuters) - Donald Tr...",1
1,#CrookedHillary’s Karma! NEW POLL Shows Trump ...,Just think how Trump s polling numbers would l...,0
2,Trump gives Boy Scouts at jamboree a taste of ...,"GLEN JEAN, West Virginia (Reuters) - After ano...",1
3,Ann Coulter Just Made The Most Despicable Cla...,In response to Trump s outrageous remarks abou...,0
4,KARMA: GAY PASTOR SUES WHOLE FOODS For “Anti-G...,Too bad for the gay pastor that Whole Foods ha...,0

In [98]:
news_dataset.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [99]:
news_dataset = news_dataset.sample(
    frac=1,
    random_state=2
).reset_index(drop=True)

news_dataset.head()

,title,text,label
0,"Nancy Pelosi Reacts To London Attack, Shows T...",Donald Trump has been in office for several mo...,0
1,Former Border Patrol officials question Trump ...,NEW YORK (Reuters) - A U.S. Department of Home...,1
2,Senate unanimously approves trade secrets bill,WASHINGTON/NEW YORK (Reuters) - The U.S. Senat...,1
3,"China says foreign press welcome, as some medi...",BEIJING (Reuters) - Chinese President Xi Jinpi...,1
4,BREAKING NEWS: Leftist Media Publishes Major F...,How many times in one week can ABC News publis...,0

In [100]:
X = news_dataset["text"]
Y = news_dataset["label"]
print(X.head())
print(Y.head())

0    Donald Trump has been in office for several mo...
1    NEW YORK (Reuters) - A U.S. Department of Home...
2    WASHINGTON/NEW YORK (Reuters) - The U.S. Senat...
3    BEIJING (Reuters) - Chinese President Xi Jinpi...
4    How many times in one week can ABC News publis...
Name: text, dtype: object
0    0
1    1
2    1
3    1
4    0
Name: label, dtype: int64

In [101]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    stratify=Y,
    random_state=2
)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (35918,)
X_test: (8980,)

In [102]:
vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (35918, 111664)
X_test shape: (8980, 111664)

In [103]:
model = LogisticRegression()

model.fit(X_train, Y_train)

LogisticRegression()

In [104]:
X_train_prediction = model.predict(X_train)

training_data_accuracy = accuracy_score(
    Y_train,
    X_train_prediction
)

print("Accuracy score of the training data:", training_data_accuracy)

Accuracy score of the training data: 0.9914527534940698

In [105]:
X_test_prediction = model.predict(X_test)

test_data_accuracy = accuracy_score(
    Y_test,
    X_test_prediction
)

print("Accuracy score of the test data:", test_data_accuracy)

Accuracy score of the test data: 0.989086859688196

In [106]:
def predict_news(news):

    news = re.sub('[^a-zA-Z]', ' ', news)
    news = news.lower()
    news = news.split()

    news = [
        stemmer.stem(word)
        for word in news
        if word not in stop_words
    ]

    news = ' '.join(news)

    news = vectorizer.transform([news])

    prediction = model.predict(news)

    if prediction[0] == 0:
        return "Fake News"
    else:
        return "True News"

In [107]:
stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()

In [108]:
def predict_news(news):

    news = re.sub('[^a-zA-Z]', ' ', news)
    news = news.lower()

    news = vectorizer.transform([news])

    prediction = model.predict(news)

    if prediction[0] == 0:
        return "Fake News"
    else:
        return "True News"

In [109]:
sample_news = news_dataset["text"].iloc[0]

print("News:")
print(sample_news)

print("\nPrediction:")
print(predict_news(sample_news))

News:
Donald Trump has been in office for several months now, and he still hasn t figured out the proper way to respond to a terrorist attack. Trump demonstrated his idiocy to the world earlier this week when he responded to the terrorist attack in London by using the tragedy as an opportunity to promote his Muslim travel ban.Trump got blasted on social media for his disgusting, insensitive response   but top Democrat Nancy Pelosi found the perfect way to slam Trump   by actually showing him how he SHOULD HAVE responded. Unlike Trump, Pelosi didn t blame London s Mayor or use it to promote any agenda. Her response was completely presidential and serves as a perfect example of how Trump should behave while completely humiliating him at the same time.In a beautiful statement of solidarity, Pelosi said: Today, the American people stand in solidarity with the people of the United Kingdom, and share in the shock and outrage of this brutal attack. We send our thoughts and prayers to the fallen, the injured and those still waiting for news of their loved ones. Terrorists will not succeed in dimming the strength and spirit of the people of the United Kingdom. Last night s vile attack   the third act of terror to target the United Kingdom in three months   was met with courage and resilience from first responders and from civilian heroes who refused to be intimidated by violence and hatred. And unlike Trump, Pelosi reached out to our allies to send a message of unity instead of divisiveness: The United States will continue to proudly work side-by-side with the U.K. to defeat terrorist threats and defend the security of all peace-loving people. May the people of the United Kingdom find solace in knowing that the American people stand with them during this difficult time. Hopefully, Trump will see Pelosi s response and a light bulb will go off in his head, but we all know he s incapable of learning from his mistakes so that s not going to happen.Pelosi s response is the kind of reaction that we d come to expect from our leaders, especially after having eight amazing years under former President Barack Obama. Unfortunately, we ve gone in quite the opposite direction under Trump. Every time there is an incident, Trump further humiliates America and insults the world with his response.Featured image via Alex Wong and Win McNamee/Getty Images

Prediction:
Fake News

In [110]:
sample_index = 0

sample_news = news_dataset["text"].iloc[sample_index]
actual_label = news_dataset["label"].iloc[sample_index]

prediction = predict_news(sample_news)

print("News:")
print(sample_news)

print("\nActual Label:")
print("Fake News" if actual_label == 0 else "True News")

print("\nPredicted Label:")
print(prediction)

News:
Donald Trump has been in office for several months now, and he still hasn t figured out the proper way to respond to a terrorist attack. Trump demonstrated his idiocy to the world earlier this week when he responded to the terrorist attack in London by using the tragedy as an opportunity to promote his Muslim travel ban.Trump got blasted on social media for his disgusting, insensitive response   but top Democrat Nancy Pelosi found the perfect way to slam Trump   by actually showing him how he SHOULD HAVE responded. Unlike Trump, Pelosi didn t blame London s Mayor or use it to promote any agenda. Her response was completely presidential and serves as a perfect example of how Trump should behave while completely humiliating him at the same time.In a beautiful statement of solidarity, Pelosi said: Today, the American people stand in solidarity with the people of the United Kingdom, and share in the shock and outrage of this brutal attack. We send our thoughts and prayers to the fallen, the injured and those still waiting for news of their loved ones. Terrorists will not succeed in dimming the strength and spirit of the people of the United Kingdom. Last night s vile attack   the third act of terror to target the United Kingdom in three months   was met with courage and resilience from first responders and from civilian heroes who refused to be intimidated by violence and hatred. And unlike Trump, Pelosi reached out to our allies to send a message of unity instead of divisiveness: The United States will continue to proudly work side-by-side with the U.K. to defeat terrorist threats and defend the security of all peace-loving people. May the people of the United Kingdom find solace in knowing that the American people stand with them during this difficult time. Hopefully, Trump will see Pelosi s response and a light bulb will go off in his head, but we all know he s incapable of learning from his mistakes so that s not going to happen.Pelosi s response is the kind of reaction that we d come to expect from our leaders, especially after having eight amazing years under former President Barack Obama. Unfortunately, we ve gone in quite the opposite direction under Trump. Every time there is an incident, Trump further humiliates America and insults the world with his response.Featured image via Alex Wong and Win McNamee/Getty Images

Actual Label:
Fake News

Predicted Label:
Fake News